import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { AnalysisResult } from '../../lib/engine';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 12, fontFamily: 'Helvetica' },
  header: { fontSize: 20, marginBottom: 20, fontWeight: 'bold', color: '#1a365d' },
  section: { marginBottom: 15, paddingBottom: 10, borderBottom: '1px solid #e2e8f0' },
  label: { fontWeight: 'bold', marginBottom: 5, color: '#4a5568' },
  value: { fontSize: 14, marginBottom: 10 },
  highlightBox: {
    marginTop: 20,
    padding: 15,
    backgroundColor: '#f7fafc',
    borderLeft: '5px solid #3182ce'
  },
  complianceText: { color: '#e53e3e', fontWeight: 'bold' }
});

export const DossierDocument = ({ data }: { data: AnalysisResult }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Customs Compliance Dossier</Text>
      
      <View style={styles.section}>
        <Text style={styles.label}>Analysis Summary</Text>
        <Text style={styles.value}>Total Weight: {data.totalWeightTonnes.toFixed(2)} Tonnes</Text>
        <Text style={styles.value}>Total Value: €{data.totalValue.toLocaleString()}</Text>
      </View>

      <View style={styles.highlightBox}>
        <Text style={styles.label}>Regulatory Requirement:</Text>
        <Text style={data.requiresY238 ? styles.complianceText : {}}>
          {data.requiresY238 
            ? "Status: THRESHOLD EXCEEDED. Declaration must include TARIC Y238." 
            : "Status: STANDARD COMPLIANCE. No additional Y238 required."}
        </Text>
      </View>

      <View style={{ marginTop: 40 }}>
        <Text style={{ fontSize: 10, color: '#a0aec0' }}>
          Generated by TradeDossier SaaS Engine v1.0. 
          Verified Date: {new Date().toLocaleDateString()}
        </Text>
      </View>
    </Page>
  </Document>
);